$(Document).ready(function () {
    $("html").css({ "background-color": "dodgerblue", "margin": "0", "padding": "0", "height": "100%" })
    $("body").css({ "background-color": "dodgerblue", "margin": "0", "padding": "0", "height": "100%" })
    $("#form1").css({ "background-color": "dodgerblue", "margin": "0", "padding": "0", "height": "100%" })
    $(".mediumScreen").css({ "position": "relative", "width": "100%", "height": "60%" })
    $(".left").css({ "position": "absolute", "left": "4%", "border-style": "solid", "width": "45%", "height": "70%", "background-color": "lightgray" })
    $(".right").css({ "position": "absolute", "right": "4%", "border-style": "solid", "width": "45%", "height": "70%", "background-color": "lightgray" })
    $(".smallScreen").css({ "position": "relative", "width": "100%", "height": "40%" })
    $(".top-left").css({ "position": "absolute", "left": "4%", "border-style": "solid", "width": "45%", "height": "44%", "background-color": "lightgray" })
    $(".bottom-left").css({ "position": "absolute", "left": "4%", "border-style": "solid", "width": "45%", "height": "44%", "background-color": "lightgray","bottom":"2px" })
    $("#lblHeatTop").css({ "color": "red", "font-style": "italic" })
    $("#lbl2").css({ "color": "red", "font-style": "italic" })
    $("#lblHeatBottom").css({ "color": "red", "font-style": "italic" })
    $("#Label1").css({ "color": "red", "font-style": "italic" })
    $("#lblPriceTop").css({ "color": "red", "font-style": "italic" })
    $("#lblPrice1").css({ "color": "red", "font-style": "italic" })
    $("#lblPriceBottom").css({ "color": "red", "font-style": "italic" })
    $("#Label2").css({ "color": "red", "font-style": "italic" })
});